@startuml
'https://plantuml.com/sequence-diagram

Celdas*-left-Recursos
Celdas*-left-Individuo
Individuo*-right-FuncionesBucle
Tablero*-left-GameOver
Tablero*-left-celdas

class Menú{

+partida(elección en pantalla)
+cargarPartida()
+nuevaPartida()

}



class Tablero{
-Fichero
+setTablero(x fila, y columnas)
+setEntorno(abria que sacar esto por pantalla )
+getDatosCasilla( x int , y int)
+Pausa(click)
+Actualizar


}
class Bucle{
-TableroDataModel
+ListaEnlazed<Celdas>

+getCelda()
+setCelda()
+ejecucion()
}
class Datos{
+mutaciones
+longevo
+reproduccionec
+MaxRep
+MaxMut
+MaxAgua

+getMutaciones()
+setMutaciones()
+getLongevo()
+setLongevo()
+getReproducciones()
+setReproducciones()
+getMaxRep()
+setMaxRep()
+getMaxMut
+setMaxMut()
+getMaxAgua()
+setMaxAgua()

}
class FuncionesBucle{
+ListaEnlazed<Recurso>
+ListaEnlazed<Individuo>
+ParameterDataModel

+FuncionesBucle(ListaEnlazed<Recurso>, ListaEnlazed<Individuo>, ParameterDataModel datos)
+Vida()
+TiempoVidaRecurso()
+BotonesDeColor(Celdas)
+Propiedades()
+getCaminoIndividuos(Individuo , ListaEnlazed<Recurso>)
+generarID()
+Reproduccion(Celdas)
+Clonacion(Celdas)
+getDescolocado(Celdas,int,int)
+getMaxVida()
}
class Celdas{
-ListaEnlazed<Individuo>
-ListaEnlazed<Recurso>
+int x
+int y
-Stage
+ParameterDataModel

+Celdas(ListaEnlazed<Individuo>, ListaEnlazed<Recurso>)
+Celdas(int,int)
+getX():int
+getY():int
+setX(int)
+setY(int)
+getDatos():datos
+ListaEnlazed<Individuo>
+getIndividuoListaEnlazed():ListaEnlazed<Individuo>
+getRecursoListaEnlazed():ListaEnlazed<Recurso>
}

class Cola{
+data
+ListaEnlazed<data>

+Cola()
+push(data)
+pull(data)
+isVacia()
}
class ElementoLe{
+data
+ElementoLe<T>
+setData(data)
+getSiguiente():ElementoLe<data>
+setSiguiente(Elemento<T>)
+InsertarmeEl(ElementoLe<data>)

}
class ElementoMap{
+data
+ElementoMap<data,E>

+ElementoMap(data,E,ElementoMap<data,E>)
+getIndice():int
+setSiguiente(ElementoMap<data,E>)
+setDato(E)
+getDato():data
}
class Generacion{


+Individuo
+Individuo
+setPadre(Individuo)
+getMadre():Individuo
+setMadre(Individuo)

}
class Historial{
+int
+Cola<String>

+Historial(int,Cola<String>)
+getMov():Cola<String>
+getTurno():int
+setMov(Cola<String>)
+añadirTurno()

}
class ListaEnlazed{
+Elemento<data>
+isVacia()
+vaciar()
+add(data)
+getNumeroElementos():int
+getPrimero():ElementoLe<data>
+getPosicion(Elemento<data>)
+getUltimo():ElementoLe<data>
+getSiguiente(ElementoLe):ElementoLe
+getElemento(int):ElementoLe
+del(int)


}
class Mapa{
+ElementoMap<data,E>
+isVacia():boolean
+put(data,E)
+get(data):E


}

class Elementos{
+agua
+comida
+montaña
+tesoro
+biblioteca
+pozo
+TasaEvolucion

+getAgua():int
+getComida():int
+getMontaña():int
+getTesoro():int
+getBiblioteca():int
+getPozo():int


+setAgua(elección en pantalla)
+setComida()
+setMontaña()
+setTesoro()
+setBiblioteca()
+setPozo()


+reproduccion( a Individuo, b Individuo)
+getArbolGenealógico( i Individuo)
+getOperaciones(p Individuo)
+getGráfica()


}
class celdas{
+getInterior()

}
class celda{
+getInterior
+

}

class Individuo{
+int
+Celdas
+ParameterDataModel
+Generacion
+Historial
+ListaEnlazed<Celdas>
+int
+int
+int
+coord
+agua
+comida
+montaña
+tesoro
+biblioteca
+pozo
+TasaEvolucion

+getAgua():int
+getComida():int
+getMontaña():int
+getTesoro():int
+getBiblioteca():int
+getPozo():int

+getTipo()
+getID()
+getVida()
+getRepro()
+getClonacion()
+getMutacion()
+getMuerte()
+getCoordenadas()


+Individuo(Celdas,int,Generacion,Historial,ListaEnlazed<Celdas>,ParameterDataModel)
+setDatos(ParameterDataModel)
+getDatos():ParameterDataModel
+setTipo()
+getTipo():int
+getGeneracion():Generacion
+setGeneracion(Generacion)

+setID()
+setVida()
+Reproduccion()
+Clonacion()
+getCelda():int
+getHistorial(Historial)
+getRuta():ListaEnlazed<Celdas>
+setRuta(ListaEnlazed<Celdas>)
+getCamino(Celdas,Celdas)
+DatosPartida(int vida, int porcentajereproduccion, int porcentajeclonacion, int porcentajetipohijo, int tiempoAparicion, int probabilidadAparicion, int probabilidadAgua, int probabilidadComida, int probabilidadBiblioteca, int probabilidadMontaña, int probabilidadPozo, int probabilidadTesoro, int filas, int columnas, ListaEnlazed<Celdas> celda) {
                      this.vida = vida)






}



class DatosPartida {
+int
+Celdas
+ParameterDataModel
+Generacion
+Historial
+ListaEnlazed<Celdas>
+int
+int
+int
+coord

+getFilas()
+getColumnas()

+getID()
+getVida()
+getRepro()
+getClonacion()
+getMutacion()
+getMuerte()
+getCoordenadas()

}

class Individuo1 extends Individuo{
+getCamino()
}
class Individuo2 extends Individuo{
+getCamino()
}
class Individuo3 extends Individuo{
+getCamino()
}

@enduml